//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStoreClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Daliveries = new HashSet<Dalivery>();
            this.ProductOrderQuantities = new HashSet<ProductOrderQuantity>();
        }
    
        public long idProduct { get; set; }
        public string Name { get; set; }
        public int idCategory { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public int idProducer { get; set; }
        public int idMeasurement { get; set; }
        public int idMarkup { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dalivery> Daliveries { get; set; }
        public virtual Markup Markup { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual Producer Producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderQuantity> ProductOrderQuantities { get; set; }
    }
}
