//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStoreClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.ProductOrderQuantities = new HashSet<ProductOrderQuantity>();
        }
    
        public int idSale { get; set; }
        public Nullable<decimal> FullPrice { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<long> idCustomer { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderQuantity> ProductOrderQuantities { get; set; }
        public virtual User User { get; set; }
    }
}
